services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - observability
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./configs/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    networks:
      - observability
    restart: unless-stopped
    depends_on:
      - tempo
      - loki
      - prometheus

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: "0:0"
    ports:
      - "3200:3200"
      - "9095:9095"
      - "4316:4317"
      - "4319:4318"
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
      - tempo-storage:/tmp/tempo
    command:
      - -config.file=/etc/tempo.yaml
    networks:
      - observability
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki.yaml:/etc/loki/local-config.yaml
      - loki-storage:/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - observability
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    networks:
      - observability
    restart: unless-stopped

volumes:
  grafana-storage:
    name: grafana-storage
  tempo-storage:
    name: tempo-storage
  loki-storage:
    name: loki-storage
  prometheus-storage:
    name: prometheus-storage

networks:
  observability:
    driver: bridge
