{
 "title": "Inference Service Dash",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Latency Metriks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(inference_api_duration_milliseconds_bucket[5m])))",
     "legendFormat": "Q50 Latency in MS"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(inference_api_duration_milliseconds_bucket[5m])))",
     "legendFormat": "Q95 Latency in MS"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(inference_api_duration_milliseconds_bucket[5m])))",
     "legendFormat": "Q99 Latency in MS"
    }
   ]
  },
  {
   "title": "Average Response Time in Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(inference_api_duration_milliseconds_sum[5m]) / rate(inference_api_duration_milliseconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Last 24Hours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(inference_api_requests_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(inference_api_requests_total{service_name=\"inference_service\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces Prediction Endpoint < 500ms",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "filters": [
      { "id": "7be4b2c5", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "inference_service" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "predict_endpoint" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1ms",
       "valueType": "duration"
      },
      {
       "id": "max-duration",
       "operator": "<",
       "tag": "duration",
       "value": "500ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Prediction Endpoint > 500ms",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "filters": [
      { "id": "266350d7", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "inference_service" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "predict_endpoint" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "500ms",
       "valueType": "duration"
      },
      {
       "id": "max-duration",
       "operator": "<",
       "tag": "duration",
       "value": "",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error Logs in Inference Service",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"inference_service\"} | json | severity = `ERROR`"
    }
   ]
  },
  {
   "title": "Warning Logs in Inference Service",
   "type": "logs",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"inference_service\"} |= `` | json | severity = `WARNING`"
    }
   ]
  },
  {
   "title": "INFO Logs in Inference Service",
   "type": "logs",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"inference_service\"} | json | severity = `INFO`"
    }
   ]
  }
 ]
}